#AWS CodeDeploy 설정

file_exists_behavior: OVERWRITE

version: 0.0
os: linux
files:
  - source: / # CodeDeploy 에서 전달해 준 파일 중 destination 으로 이동시킬 대상 지정 [루트 경로(/) 지정 시 전체 파일]
    destination: /home/ec2-user/us-server/
#  - source: /
#    destination: /home/api

permissions: # CodeDeploy 에서 EC2 서버로 넘겨준 파일들 권한 설정
  - object: /home/api/
    pattern: '**'
    owner: ec2-user
    group: ec2-user
#
#hooks: # CodeDeploy 배포 단계에서 실행할 명령어 지정
#  ApplicationStart:
#    - location: scripts/deploy.sh
#      timeout: 300 # 스크릡트 실행 시간 5분 넘억면 실패
#      runas: root
##