version: 0.0
os: linux
files:
  - source: /
    destination: /home/api/server
  - source: /.env
    destination: /home/api
  - source: /config/
    destination: /home/api/config
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/api
    pattern: '**'
    mode: '755'
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/after-deploy.sh
      timeout: 2000
      runas: root